// ─────────────────────────────────────────────────────────────────────────────
// models/User.js — USER SCHEMA (DATABASE SHAPE)
//
// A "model" defines the shape of a document in MongoDB.
// Think of it like a form — it says what fields are allowed,
// what types they must be, and which ones are required.
//
// This file also handles password hashing and comparison.
// ─────────────────────────────────────────────────────────────────────────────

// mongoose lets us define schemas and interact with MongoDB
const mongoose = require('mongoose');

// bcryptjs is used to securely hash passwords before saving them.
// Hashing = turning "password123" into a random unreadable string.
// We NEVER store plain text passwords in the database.
const bcrypt = require('bcryptjs');

// Import system constants
const { ROLES } = require('../utils/constants');


// ─── DEFINE THE SCHEMA ────────────────────────────────────────────────────────
// A schema is a blueprint that describes what a User document looks like.
// Every user saved to MongoDB will have these exact fields.
const userSchema = new mongoose.Schema({

  // name field — must be a string, and it is required
  name: {
    type: String,
    required: [true, 'Please provide a name'], // [condition, error message]
  },

  // email field — must be a string, must be unique (no two users share an email)
  // lowercase: true automatically converts the email to lowercase before saving
  email: {
    type: String,
    required: [true, 'Please provide an email'],
    unique: true,      // MongoDB will reject duplicate emails
    lowercase: true,   // "User@Test.com" → saved as "user@test.com"
  },

  // password field — must be at least 8 characters
  // select: false means this field is HIDDEN by default on queries.
  // If you query User.findOne({email}), password will NOT be included.
  // To include it you must explicitly say .select('+password').
  password: {
    type: String,
    required: [true, 'Please provide a password'],
    minlength: 8,
    select: false,  // hidden by default — for security
  },

  // role field — can only be one of these three values
  // enum restricts the allowed values
  // default: ROLES.USER means if no role is provided, it becomes 'user'
  role: {
    type: String,
    enum: Object.values(ROLES), // ['user', 'agent', 'admin']
    default: ROLES.USER,
  },

  // agentSecurityCode — only set for agents, used to validate agent login
  // select: false means it's hidden by default — only admins should see it
  // This is a unique code generated by the admin for each agent
  agentSecurityCode: {
    type: String,
    select: false,  // hidden by default — for security
    default: null,  // null if user is not an agent
  },

  // createdAt — automatically set to the current date when user is created
  createdAt: {
    type: Date,
    default: Date.now, // Date.now returns the current timestamp
  },
});


// ─── PRE-SAVE HOOK ────────────────────────────────────────────────────────────
// A "hook" is a function that runs automatically at a certain moment.
// 'pre("save")' means: "run this function BEFORE saving a user to the database".
//
// Why do we need this?
//   When a user registers, their password is plain text ("password123").
//   We need to hash it before saving — so "password123" becomes something
//   like "$2b$10$Nm8...xK" that cannot be reversed back to the original.
//
// IMPORTANT: We use a regular function (not arrow function) here because
// 'this' refers to the user document being saved. Arrow functions don't
// have their own 'this' and would break this hook.
userSchema.pre('save', async function () {
  // isModified('password') checks if the password field was changed.
  // If password was NOT changed (e.g. we updated only the name),
  // we skip hashing and return early. Without this early return,
  // the password would be re-hashed every time the user is saved — a bug!
  if (!this.isModified('password')) return;

  // genSalt(10) creates a random "salt" — a value mixed into the hash
  // to make it unique. 10 is the cost factor (higher = more secure but slower).
  const salt = await bcrypt.genSalt(10);

  // bcrypt.hash() takes the plain text password and the salt,
  // and returns a hashed version. We overwrite this.password with the hash.
  this.password = await bcrypt.hash(this.password, salt);
});


// ─── comparePassword METHOD ────────────────────────────────────────────────────
// A custom method we add to every User document.
// Called at login to check if the password the user typed matches the stored hash.
//
// bcrypt.compare() returns true if they match, false if they don't.
// It handles the hashing internally — we just pass the plain text and the hash.
//
// Usage: const isMatch = await user.comparePassword('password123');
userSchema.methods.comparePassword = async function (candidatePassword) {
  return bcrypt.compare(candidatePassword, this.password);
};


// ─── generateSecurityCode STATIC METHOD ────────────────────────────────────────
// Generates a random 6-digit security code for agents
// Returns a string like "AB3XZ9"
// Usage: const code = User.generateSecurityCode();
userSchema.statics.generateSecurityCode = function () {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 6; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
};


// ─── CREATE & EXPORT THE MODEL ────────────────────────────────────────────────
// mongoose.model('User', userSchema) creates a Model from the schema.
// The first argument 'User' is the model name — Mongoose will look for
// a collection called 'users' in MongoDB (it lowercases and pluralises).
module.exports = mongoose.model('User', userSchema);
